# Generated by Django 2.1.2 on 2018-10-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formeditor', '0002_auto_20181003_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_tilte', models.CharField(blank=True, max_length=300, null=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formeditor.Post'),
        ),
    ]
