# Generated by Django 2.1.2 on 2018-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formeditor', '0003_auto_20181006_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_tilte',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
