# Generated by Django 2.1.2 on 2018-10-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formeditor', '0004_auto_20181006_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video_tilte',
            new_name='video_title',
        ),
    ]
