# Generated by Django 2.1.2 on 2018-10-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formeditor', '0007_auto_20181006_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formeditor.Video'),
        ),
    ]
